python: can't open file '/home/rliubk/llm-project/werewolf_game_reasoning/compare_models.py': [Errno 2] No such file or directory
